# Generated by Django 5.0.6 on 2024-05-13 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_paymentchannel_business_profile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsremitted',
            name='payment_success_message',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LiquidationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('in_review', 'In Review'), ('processed', 'Processed')], default='in_review', max_length=20, null=True)),
                ('reason_for_liquidation', models.TextField(blank=True, null=True)),
                ('estimated_value_of_goods', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('anticipated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiquidationRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('item_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('GoodImg1', models.ImageField(blank=True, null=True, upload_to='liquidation_goods_images')),
                ('GoodImg2', models.ImageField(blank=True, null=True, upload_to='liquidation_goods_images')),
                ('GoodImg3', models.ImageField(blank=True, null=True, upload_to='liquidation_goods_images')),
                ('liquidation_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.liquidationrequest')),
            ],
        ),
    ]
