# Generated by Django 5.0.6 on 2024-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_resetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsremitted',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
