# Generated by Django 5.0.6 on 2024-05-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_businessprofile_business_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liquidationrequestitem',
            name='liquidation_request',
        ),
        migrations.AddField(
            model_name='liquidationrequest',
            name='goods_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='GoodsSoldStatistics',
        ),
        migrations.DeleteModel(
            name='LiquidationRequestItem',
        ),
    ]
