# Generated by Django 5.0.6 on 2024-05-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_liquidationrequestitem_liquidation_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationrequest',
            name='condition_of_goods',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used_good', 'Used - Good condition'), ('used_fair', 'Used - Fair condition'), ('damaged', 'Damaged')], default='new', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='liquidationrequest',
            name='quantity_goods',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
