# Generated by Django 5.0.6 on 2024-05-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_liquidationrequest_condition_of_goods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liquidationrequestfeedback',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='liquidationrequest',
            name='goods_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='liquidationrequest',
            name='quantity_goods',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
