# Generated by Django 5.0.6 on 2024-05-14 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_liquidationrequestfeedback_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsremitted',
            name='business_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.businessprofile'),
        ),
    ]
